---
driver:
  name: vagrant
  forward_agent: true

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 12
  data_bags_path: 'test/data_bags'


platforms:
  - name: ubuntu-18.04
    driver:
      provider: virtualbox
      box: bento/ubuntu-18.04
      customize:
        memory: 2048

verifier:
  name: inspec

suites:
  - name: app-cache01
    provisioner:
      policyfile_path: policyfiles/app-cache.rb
    driver:
      network:
        - ['private_network', {ip: '192.168.34.13'}]
    attributes:
      zeit_rz: local
      corosync: {clustername: 'kitchen'}

  - name: app-cache02
    provisioner:
      policyfile_path: policyfiles/app-cache.rb
    driver:
      network:
        - ['private_network', {ip: '192.168.34.14'}]
    attributes:
      zeit_rz: local
      corosync: {clustername: 'kitchen'}
