---
driver:
  name: vagrant
  forward_agent: true
  box_check_update: false

# Work around <https://github.com/test-kitchen/test-kitchen
#  /issues/1035#issuecomment-283189967>
transport:
  max_ssh_sessions: 5

provisioner:
  name: chef_zero
  require_chef_omnibus: 13

platforms:
  - name: ubuntu-18.04
    <% if ENV["KITCHEN_PROVIDER"] == "virtualbox" %>
    driver:
      provider: virtualbox
      box: bento/ubuntu-18.04
      customize:
        memory: 2048
    <% else %>
    driver:
      box: emptybox/ubuntu-bionic-amd64-lxc
      provider: lxc
    <% end %>

verifier:
  name: inspec
  <% if ENV["KITCHEN_FORMAT"] == "junit" %>
  format: junit
  output: report_integration_%{suite}.xml
  <% end %>

suites:
  - name: batou-app-cache
    run_list:
      - recipe[zeit-batou-target]
      - recipe[zeit-app-cache::varnish]
    attributes:
      batou:
        serviceUsers: ['app-cache']
        varnish_config:
          - "/srv/app-cache/deployment/work/varnish/default.vcl"
          - "/srv/app-cache/deployment/work/varnish/vcl_includes"
