---
driver:
  name: vagrant
  forward_agent: true

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 12


platforms:
  - name: ubuntu-18.04
    <% if ENV["KITCHEN_PROVIDER"] == "virtualbox" %>
    driver:
      provider: virtualbox
      box: bento/ubuntu-16.04
      customize:
        memory: 2048
    <% else %>
    driver:
      box: developerinlondon/ubuntu_lxc_xenial_x64
      provider: lxc
    <% end %>

verifier:
  name: inspec
  <% if ENV["KITCHEN_FORMAT"] == "junit" %>
  format: junit
  output: report_integration_%{suite}.xml
  <% end %>

suites:
  - name: app-cache
    provisioner:
      policyfile_path: policyfiles/app-cache.rb
    driver:
      network:
        - ['private_network', {ip: '192.168.34.13'}]
    attributes: 
      batou:
        varnish_config: 
          - "/srv/app-cache/deployment/work/varnish/default.vcl"
          - "/srv/app-cache/deployment/work/varnish/vcl_includes"
