---
driver:
  name: vagrant

# Work around <https://github.com/test-kitchen/test-kitchen
#  /issues/1035#issuecomment-283189967>
transport:
  max_ssh_sessions: 5

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14

platforms:
  - name: ubuntu-18.04
    <% if ENV["KITCHEN_PROVIDER"] == "virtualbox" %>
    driver:
      provider: virtualbox
      box: bento/ubuntu-18.04
      customize:
        memory: 2048
    <% else %>
    driver:
      box: zeitonline/bionic64-lxc
      provider: lxc
    <% end %>

verifier:
  name: inspec
  reporter:
    - cli
  <% if ENV["KITCHEN_FORMAT"] == "junit" %>
    - junit:report_integration_%{suite}.xml
  <% end %>

suites:
  - name: batou-app-cache
    run_list:
      - recipe[zeit-baseserver::kitchen]
      - recipe[zeit-baseserver]
      - recipe[zeit-app-cache]
      - recipe[zeit-app-cache::role-haproxy]
    attributes:
      varnish:
        storage-size: 32M
